[package]
name = "warphorizon-client-glium"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
cgmath = "0.7.0"
glium = "0.13.5"
wavefront_obj = "3.0.0"

[dependencies.warphorizon-client]
path = "../../libraries/client"
