[package]
name = "warp-horizon-client"
version = "0.1.0"
authors = ["Layl <layl@edgeworksgames.com>"]

[dependencies]
cgmath = "0.7"
enum_primitive = "0.1"
time = "0.1"

[dependencies.warp-horizon]
path = "../../libraries/warp_horizon"
