[package]
name = "tungsten-glium2d"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
dynamic = "0.2.1"
glium = "0.13.5"

[dependencies.tungsten]
path = "../../libraries/tungsten"
