[package]
name = "client"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies.tungsten]
path = "../../libraries/tungsten"

[dependencies.tungsten-glium2d]
path = "../../libraries/tungsten-glium2d"
