[package]
name = "warp-horizon-client"
version = "0.1.0"
authors = ["Layl <layl@edgeworksgames.com>"]

[dependencies]
cgmath = "0.5"
glium = "0.12"
image = "0.5"

[dependencies.warp-horizon]
path = "../../libraries/warp_horizon"
